name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Installer requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Exécuter les tests
        working-directory: src
        run: python3 -m pytest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Déploiement local
        run: |
          cd $GITHUB_WORKSPACE
          echo "Déploiement sur la VM en cours..."
          docker compose down || true
          docker compose up -d --build
