name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ajout explicite

      - name: Debug - Afficher le contenu
        run: |
          ls -la
          ls -la src

      - name: Exécuter les tests
        env:
          PYTHONPATH: src
        run: pytest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Déploiement local
        run: |
          echo "Déploiement sur la VM en cours..."
          docker compose down || true
          docker compose up -d --build
