name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Vérifier la version de Python
        run: python3.11 --version

      - name: Installer les dépendances
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r requirements.txt
          python3.11 -m pip install pytest

      - name: Debug - Afficher le contenu
        run: |
          ls -la
          ls -la src

      - name: Exécuter les tests
        env:
          PYTHONPATH: src
        run: python3.11 -m pytest

  deploy:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Déploiement local
        run: |
          echo "Déploiement sur la VM en cours..."
          docker compose down || true
          docker compose up -d --build
